### ISSUE TITLE
TypeError: request.data is null

### ISSUE THREAD

**Issue by ajsb85** [davidevernizzi/docman#9] opened 2016-05-02 16:39 UTC
```
18:38:23.530 TypeError: request.data is null
[247]</RequestData<.render()main.js:34221
[133]</</ReactCompositeComponentMixin._renderValidatedComponent<()main.js:20965
[167]</</ReactPerf.measure/wrapper()main.js:26808
[133]</</ReactCompositeComponentMixin.mountComponent<()main.js:20507
[167]</</ReactPerf.measure/wrapper()main.js:26808
[163]</ReactMultiChild.Mixin.mountChildren()main.js:26262
[138]</</ReactDOMComponent.Mixin._createContentMarkup()main.js:21749
[138]</</ReactDOMComponent.Mixin.mountComponent<()main.js:21671
[167]</</ReactPerf.measure/wrapper()main.js:26808
[133]</</ReactCompositeComponentMixin.mountComponent<()main.js:20513
[167]</</ReactPerf.measure/wrapper()main.js:26808
[163]</ReactMultiChild.Mixin.mountChildren()main.js:26262
[138]</</ReactDOMComponent.Mixin._createContentMarkup()main.js:21749
[138]</</ReactDOMComponent.Mixin.mountComponent<()main.js:21671
[167]</</ReactPerf.measure/wrapper()main.js:26808
[133]</</ReactCompositeComponentMixin.mountComponent<()main.js:20513
[167]</</ReactPerf.measure/wrapper()main.js:26808
[163]</ReactMultiChild.Mixin.mountChildren()main.js:26262
[138]</</ReactDOMComponent.Mixin._createContentMarkup()main.js:21749
[138]</</ReactDOMComponent.Mixin.mountComponent<()main.js:21671
[167]</</ReactPerf.measure/wrapper()main.js:26808
[133]</</ReactCompositeComponentMixin.mountComponent<()main.js:20513
[167]</</ReactPerf.measure/wrapper()main.js:26808
[163]</ReactMultiChild.Mixin.mountChildren()main.js:26262
[138]</</ReactDOMComponent.Mixin._createContentMarkup()main.js:21749
[138]</</ReactDOMComponent.Mixin.mountComponent<()main.js:21671
[167]</</ReactPerf.measure/wrapper()main.js:26808
[163]</ReactMultiChild.Mixin.mountChildren()main.js:26262
[138]</</ReactDOMComponent.Mixin._createContentMarkup()main.js:21749
[138]</</ReactDOMComponent.Mixin.mountComponent<()main.js:21671
[167]</</ReactPerf.measure/wrapper()main.js:26808
[133]</</ReactCompositeComponentMixin.mountComponent<()main.js:20513
[167]</</ReactPerf.measure/wrapper()main.js:26808
[163]</ReactMultiChild.Mixin._mountChildByNameAtIndex()main.js:26462
[163]</ReactMultiChild.Mixin._updateChildren()main.js:26367
[163]</ReactMultiChild.Mixin.updateChildren()main.js:26314
[138]</</ReactDOMComponent.Mixin._updateDOMChildren()main.js:21946
[138]</</ReactDOMComponent.Mixin.updateComponent<()main.js:21799
[167]</</ReactPerf.measure/wrapper()main.js:26808
[131]</</ReactComponent.Mixin.performUpdateIfNecessary()main.js:19466
[131]</</ReactComponent.Mixin.receiveComponent()main.js:19447
[138]</</ReactDOMComponent.Mixin.receiveComponent()main.js:21772
[133]</</ReactCompositeComponentMixin.updateComponent<()main.js:20894
[167]</</ReactPerf.measure/wrapper()main.js:26808
[133]</</ReactCompositeComponentMixin._performComponentUpdate()main.js:20836
[133]</</ReactCompositeComponentMixin.performUpdateIfNecessary()main.js:20779
[131]</</ReactComponent.Mixin.receiveComponent()main.js:19447
[133]</</ReactCompositeComponentMixin.receiveComponent()main.js:20862
[163]</ReactMultiChild.Mixin._updateChildren()main.js:26354
[163]</ReactMultiChild.Mixin.updateChildren()main.js:26314
[138]</</ReactDOMComponent.Mixin._updateDOMChildren()main.js:21946
[138]</</ReactDOMComponent.Mixin.updateComponent<()main.js:21799
[167]</</ReactPerf.measure/wrapper()main.js:26808
[131]</</ReactComponent.Mixin.performUpdateIfNecessary()main.js:19466
[131]</</ReactComponent.Mixin.receiveComponent()main.js:19447
[138]</</ReactDOMComponent.Mixin.receiveComponent()main.js:21772
[133]</</ReactCompositeComponentMixin.updateComponent<()main.js:20894
[167]</</ReactPerf.measure/wrapper()main.js:26808
[133]</</ReactCompositeComponentMixin._performComponentUpdate()main.js:20836
[133]</</ReactCompositeComponentMixin.performUpdateIfNecessary()main.js:20779
[131]</</ReactComponent.Mixin.receiveComponent()main.js:19447
[133]</</ReactCompositeComponentMixin.receiveComponent()main.js:20862
[163]</ReactMultiChild.Mixin._updateChildren()main.js:26354
[163]</ReactMultiChild.Mixin.updateChildren()main.js:26314
[138]</</ReactDOMComponent.Mixin._updateDOMChildren()main.js:21946
[138]</</ReactDOMComponent.Mixin.updateComponent<()main.js:21799
[167]</</ReactPerf.measure/wrapper()main.js:26808
[131]</</ReactComponent.Mixin.performUpdateIfNecessary()main.js:19466
[131]</</ReactComponent.Mixin.receiveComponent()main.js:19447
[138]</</ReactDOMComponent.Mixin.receiveComponent()main.js:21772
[163]</ReactMultiChild.Mixin._updateChildren()main.js:26354
[163]</ReactMultiChild.Mixin.updateChildren()main.js:26314
[138]</</ReactDOMComponent.Mixin._updateDOMChildren()main.js:21946
[138]</</ReactDOMComponent.Mixin.updateComponent<()main.js:21799
[167]</</ReactPerf.measure/wrapper()main.js:26808
[131]</</ReactComponent.Mixin.performUpdateIfNecessary()main.js:19466
[131]</</ReactComponent.Mixin.receiveComponent()main.js:19447
[138]</</ReactDOMComponent.Mixin.receiveComponent()main.js:21772
[133]</</ReactCompositeComponentMixin.updateComponent<()main.js:20894
[167]</</ReactPerf.measure/wrapper()main.js:26808
[133]</</ReactCompositeComponentMixin._performComponentUpdate()main.js:20836
[133]</</ReactCompositeComponentMixin.performUpdateIfNecessary()main.js:20779
runBatchedUpdates()main.js:28125
[194]</</Mixin.perform()main.js:29863
[194]</</Mixin.perform()main.js:29863
[178]</</<.perform()main.js:28071
[178]</</flushBatchedUpdates<()main.js:28150
[167]</</ReactPerf.measure/wrapper()main.js:26808
bound ()self-hosted
[194]</</Mixin.closeAll()main.js:29936
[194]</</Mixin.perform()main.js:29877
[147]</ReactDefaultBatchingStrategy.batchedUpdates()main.js:23090
batchedUpdates()main.js:28086
[156]</ReactEventListener.dispatchEvent()main.js:24554
bound ()self-hosted
1main.js:34221:1

```

**Comment by rowasc** [comment] 2016-06-28 01:31
@ajsb85 Hi, sorry for the delay, but if you could provide a simple way to reproduce this, I would really appreciate it.  I should be fixed in #8 since it handled the request.data being null, but just in case it's a different situation..
Thanks
Romina

**Comment by ajsb85** [comment] 2016-06-28 09:13
I leave the project, I will try to return soon.

**Comment by rowasc** [comment] 2016-09-03 19:45
I'm closing the issue due to inactivity. If the problem persists, please file a new issue with an example of the data being used.

**Closed as completed by rowasc** 2016-09-03 19:45 UTC
